### ISSUE TITLE
Transfer Files/Folders in Created Session

### ISSUE THREAD

**Issue by HRNasr** [casvisor/casvisor#100]
Add Feature transfer file/folders in created session (RDP/SSH,...) with Drag and Drop or normal method.
RDP: Transfer file with define dedicated drive in session
SSH: Transfer file in OS
...

EX: Next-Teminal, Jump-Server

**Comment by hsluoyz** [comment]
@HRNasr file manager is already supported by PR: https://github.com/casvisor/casvisor/pull/86 . It relies on SFTP which is based on SSH (like WinSCP). AFAIK, RDP doesn't support file transfer itself. So it's also SSH for Windows asset. (Windows can install OpenSSH server)

See demo: https://door.casvisor.com/assets

![image](https://github.com/casvisor/casvisor/assets/3787410/e3371a29-b1b9-4743-a824-00a442d3c161)
